config/routes.rb
Rails.application.routes.draw do
  resources :video_sources, only: %i[create]
  resources :videos, only: %i[index]
  root 'videos#index'
  get '/share', to: 'video_sources#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_length_of :password, minimum: 6, maximum: 20

  before_validation :downcase_email

  private

  def downcase_email
    self.email = email.downcase if email.present?
  end
end

app/models/user_reaction.rb
class UserReaction < ApplicationRecord
  validates :user_id, :video_id, presence: true
  validates :reaction, presence: true
  enum reaction: {like: 0, dislike: 1}

  belongs_to :video

  after_save :refresh_video_meta_information
  after_destroy :refresh_video_meta_information

  private

  def refresh_video_meta_information
    video.refresh_reactions_count
  end
end

app/models/video.rb
class Video < ApplicationRecord
  validates :title, :video_source_id, presence: true

  belongs_to :video_source
  belongs_to :user, optional: true
  has_many :user_reactions

  delegate :identify_id, to: :video_source, prefix: false
  delegate :email, to: :user, prefix: true, allow_nil: true

  def refresh_reactions_count
    reaction_count = user_reactions.group(:reaction).count
    attrs = {
      likes_count: reaction_count['like'].to_i,
      dislikes_count: reaction_count['dislike'].to_i
    }
    self.update_columns(attrs)
  end
end

app/models/video_source.rb
class VideoSource < ApplicationRecord
  PROVIDER_DOMAINS = {'www.youtube.com' => :youtube, 'youtube.com' => :youtube, 'youtu.be' => :youtube}
  enum provider: { youtube: 1 }
  validates :provider, presence: true
  validates :identify_id, presence: true
  attr_accessor :video_url
  before_validation :parse_url, on: :create

  private

  def parse_url
    return if provider.present? && identify_id.present?
    return errors.add(:video_url, 'blank') if video_url.blank?
    uri = URI.parse(video_url)
    return errors.add(:video_url, 'invalid format') unless uri.kind_of?(URI::HTTP) || uri.kind_of?(URI::HTTPS)
    self.provider = PROVIDER_DOMAINS[uri.host]
    errors.add(:provider, 'unsupported provider') if self.provider.blank?
    self.identify_id = identify_id_by_uri(uri)
  end

  def identify_id_by_uri uri
    return unless self.youtube?
    Rack::Utils.parse_query(uri.query)['v'] || uri.path.split('/').reject(&:blank?).last 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user


  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  private

  def authorized
    redirect_to root_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    service = RegistrationOrLoginService.new(login_params[:email], login_params[:password])
    login_process = service.execute
    if login_process[:status]
      session[:user_id] = login_process[:user_id]
      flash.now[:success] = "Login Success."
      redirect_to root_path
    else
      flash.now[:alert] = login_process[:error]
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
    def login_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/video_sources_controller.rb
class VideoSourcesController < ApplicationController
  # before_action :authorized

  def new
    @video_source = VideoSource.new
  end

  def index
    @video_sources = VideoSource.all
  end

  def create
    @video_source = VideoSource.new(video_source_params)
    service = GenerateVideoService.new(@video_source)
    service.user_id = current_user&.id
    status = service.execute
    respond_to do |format|
      if status
        format.html { redirect_to videos_url, notice: "Video was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def video_source_params
      params.require(:video_source).permit(:video_url)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all.includes(:video_source).order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_sources_helper.rb
module VideoSourcesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ytbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= render "layouts/navbar" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |key, value| %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block <%= key %>"><%= value %></p>
  <% end %>
<% end %>
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>

app/views/video_sources/_form.html.erb
<%= form_with(model: video_source, class: "contents") do |form| %>
  <% if video_source.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(video_source.errors.count, "error") %> prohibited this video_source from being saved:</h2>

      <ul>
        <% video_source.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :video_url %>
    <%= form.text_field :video_url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/video_sources/_video_source.html.erb
<div id="<%= dom_id video_source %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Provider:</strong>
    <%= video_source.provider %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Identify:</strong>
    <%= video_source.identify_id %>
  </p>
</div>

app/views/video_sources/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Videos</h1>
    <%= link_to 'New video', share_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="video_sources" class="min-w-full">
    <%= render @video_sources %>
  </div>
</div>

app/views/video_sources/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New video</h1>
  <%= render "form", video_source: @video_source %>
  <%= link_to 'Back to videos', root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/videos/_video.html.erb
<div class="flex flex-col sm:flex-row bg-white overflow-hidden shadow-xl mt-3 mb-3" id="<%= dom_id video %>">
  <div class="basis-1/2 sm:basis-full">
    <div class="relative h-0 overflow-hidden max-w-full w-full" style="padding-bottom: 56.25%">
      <iframe src="https://www.youtube.com/embed/<%= video.identify_id %>" frameborder="0" allowfullscreen class="absolute top-0 left-0 w-full h-full" ></iframe>
    </div>
  </div>
  <div class="basis-1/2 sm:basis-full p-8 text-center md:text-left space-y-4 bg-slate-100">
    <div class="font-medium text-sm leading-6 text-indigo-600">
      <%= video.user_email || "Admin" %>
    </div>
    <h3 class="block font-bold text-base leading-4 dark:text-white text-ellipsis overflow-hidden ">
      <%= video.title.html_safe %>
    </h3>
    <div class="text-sm text-slate-600 leading-6 overflow-auto max-h-48">
      <%= simple_format video.description.html_safe %>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Videos</h1>
  </div>
  <div id="videos" class="min-w-full">
    <%= render @videos %>
  </div>
</div>